services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleetify_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    ports:
      - "3000:3000"
